### ISSUE TITLE
Fix without media query

### ISSUE THREAD

**Issue by fregante** [postcss/postcss-100vh-fix#1]
```css
body {
  height: 100vh;
}
```
should be fixed to

```css
body {
  height: 100vh;
  height: -webkit-fill-available;
}
```

`-webkit-fill-available` is automatically ignored by browsers that don't understand it.

**Comment by simevidas** [comment]
It causes issues in Chrome: https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/#comment-4910262284

> When I first load this page in Chrome on Android, the MAIN element is several screens large for some reason, and I have to scroll down to get to the footer (first screenshot).
But then when I pull-to-refresh, the page renders correctly (second screenshot).

**Comment by kripod** [comment]
Does the snippet used [on CSS Tricks](https://css-tricks.com/css-fix-for-100vh-in-mobile-webkit/) solve the issue?

```css
body {
  min-height: 100vh;
  min-height: -webkit-fill-available;
}
html {
  height: -webkit-fill-available;
}
```
