### ISSUE TITLE
Include important flag if necessary

### ISSUE THREAD

**Issue by CaitlinWeb-st** [postcss/postcss-100vh-fix#3]
Style declarations with `!important` aren't being overruled by this plugin. For my use case I'm using Bootstrap which has `.vh-100` with the important flag. Here's what this plugin results in:

```css
.vh-100 {
  height: 100vh !important; }
@supports (-webkit-touch-callout: none) {
  .vh-100 {
    height: -webkit-fill-available; } }
```

This means `100vh` wins since it's declared with `!important`.
