### ISSUE TITLE
Handling width, min-width, max-width

### ISSUE THREAD

**Issue by smashercosmo** [postcss/postcss-100vh-fix#7]
I'm wondering should plugin also handle width, min-width and max-width? Could be useful in cases like

```css
.class {
  width: 100vh;
  transform: rotate(90deg);
}
```
